### ISSUE TITLE
What is the correct way to set up the package.js with reactive-templates?

### ISSUE THREAD

**Issue by thetechnaddict** [nicolaslopezj/reactive-templates#2]
Please be patient a little while. I think my error is in my package.js file - 

I have included this line:

```
api.use(['nicolaslopezj:reactive-templates@1.2.0'], ['client']);
```

The problem - 

I am adapting a package to use reactive-templates.

When the code is placed in an app, rather than in a package, all works very sweetly. I can override the templates.

When I move the code into a local package then it does not work.

First symptom is a reference error - ReactiveTemplates is undefined.

When I add my package nicolaslopezj:reactive-templates is listed in the dependencies added 

However when, as an experiment I add the package to the app the referenceerror goes away but the template handlers etc.. are not assigned.

Hence I am doubting that reactive-templates has been really added by the package.

**Comment by nicolaslopezj** [comment]
Add reactive templates to `api.imply`

``` js
api.imply([
    'nicolaslopezj:reactive-templates'
]);
```

https://github.com/orionjs/orion/blob/master/packages/base/package.js#L27

**Comment by thetechnaddict** [comment]
That was a 10 second response time - I do which I was that fast!

Many thanks

**Comment by nicolaslopezj** [comment]
You're welcome!

Did it work?

**Comment by thetechnaddict** [comment]
The error reference has gone but I have uncaught error - no such function - I think because the handlers are not being assigned to the template that is now correctly set 

(in the console ReactiveTemplates.get() returns the template I have set.)

**Comment by nicolaslopezj** [comment]
Show me the code that has that error

**Comment by thetechnaddict** [comment]
Actually the code failing is in the js file which has no handlers etc... it is null other than the set commands.

``` js
    ReactiveTemplates.set( 'blogList', 'reclaimBlogList' );
    ReactiveTemplates.set( 'blogPost', 'reclaimBlogPost' );
    ReactiveTemplates.set( 'blogControls', 'reclaimBlogControls' );
```

The template in the app (still messy as in the process of change)

``` html
    <template name="reclaimBlogList">
      {{#if isInRole 'mdblog-author'}}
          <section class="blog-controls">
              <button title="New" id="mdblog-new" class="{{mdBlogElementClasses 'button-new'}}">
                  <i class="{{mdBlogElementClasses 'button-icon-new'}}"></i>{{_ "new"}}</button>
          </section>
      {{/if}}
        <section class="collection">
          {{#each this}}
              <section class="blog-post collection-item">
                {{#if isInRole 'mdblog-author'}}
                    {{> Template.dynamic template=blogControlTemplate}}
                {{/if}}
                  <header>
                  <h2><a href="{{pathFor route='blogPost'}}">{{title}}</a></h2>
                              <span class="info">{{_ "posted_by"}}<span class="author">{{author}}</span>
                                  <time>{{mdBlogDate date}}</time>
                              </span>
                      </header>
                  <summary>
                    {{{summary}}} <a href="{{pathFor route='blogPost'}}">{{_ "read_more"}}
                      <i class="fa fa-long-arrow-right"></i></a>
                  </summary>
                 </section>
          {{else}}
              {{_ "waiting_for_posts"}}
          {{/each}}
        </section>
    </template>

    <template name="reclaim-blogControls">
        <section class="blog-controls">
          {{#if modified}}
              <button title="Save" id="mdblog-save" class="{{mdBlogElementClasses 'button'}}">
                  <i class="fa fa-floppy-o">{{_ "save"}}</i>
              </button>
          {{/if}}
          {{#unless published}}
              <button title="Publish" id="mdblog-publish" class="{{mdBlogElementClasses 'button'}}">
                  <i class="fa fa-play"></i>{{_ "publish"}}</button>
          {{/unless}}
          {{#if published}}
              <button title="Unpublish" id="mdblog-unpublish" class="{{mdBlogElementClasses
              'button'}}"><i class="fa fa-stop"></i>{{_ "unpublish"}}</button>
          {{/if}}
          {{#unless archived}}
              <button title="Archive" id="mdblog-archive" class="{{mdBlogElementClasses 'button'}}">
                  <i class="fa fa-eye-slash"></i>{{_ "archive"}}</button>
          {{/unless}}
          {{#if archived}}
              <button title="Unarchive" id="mdblog-unarchive" class="{{mdBlogElementClasses 'button'}}">
                  <i class="fa fa-eye"></i>{{_ "unarchive"}}</button>
          {{/if}}
            <button title="Delete" id="mdblog-delete" class="{{mdBlogElementClasses 'button'}}">
                <i class="fa fa-trash"></i>{{_ "delete"}}</button>
        </section>
    </template>

    <template name="reclaim-blogPost">
      {{#if blogPostReady}}
          <section class="blog-post">
              <header>
                {{#if isInRole 'mdblog-author'}}
                    {{> Template.dynamic template=blogControlTemplate}}
                {{/if}}
                  <h1 id="title" {{contenteditable}}>{{{title}}}</h1>
                  <p>sing it now</p>

                  <h3 id="summary" {{contenteditable}}>{{{summary}}}</h3>
                <span class="info">{{_ "posted_by"}}
                    <span id="author" class="author" {{contenteditable}}>{{{author}}}</span>
                    <time id="date" {{contenteditable}}>{{mdBlogDate date}}</time>
                </span>
                {{#if allowPictureUpload}}
                  <br />
                  <button title="Picture" id="mdblog-picture" class="{{mdBlogElementClasses 'button'}}">
                    <i class="fa fa-image"></i> {{_ "picture"}}
                  </button>
                  <input type="file" id="mdblog-file-input" style="display:none;" accept="image/*" multiple />
                {{/if}}
              </header>
              <article id="content" {{contenteditable}} data-markdown="true">
                {{{content}}}
              </article>
          </section>
      {{else}}
          {{_ "loading"}}
      {{/if}}
    </template>
```

Template from the package is identical but loads when not overridden.

**Comment by thetechnaddict** [comment]
here are the events and handlers that should be loading but are not...

``` js
        // ***********************************************************************************************
    // **** Blog List

    ReactiveTemplates.request('blogList', 'mdBlogBlogList')

    ReactiveTemplates.onRendered('blogList', function () {
      Tracker.autorun(function() {
        Session.get('locale'); // force dependency
        _setMetadata({
           title: TAPi18n.__("name"),
          description: TAPi18n.__("description")
        });
      });
    });

    var _setMetadata = function (meta) {
      if (meta.title) {
        document.title = meta.title;
        delete meta.title;
      }
      for (var key in meta) {
        $('meta[name="' + key + '"]').remove();
        $('head').append('<meta name="' + key + '" content="' + meta[key] + '">');

        $('meta[property="og:' + key + '"]').remove();
        $('head').append('<meta property="og:' + key + '" content="' + meta[key] + '">');
      }
    };

    ReactiveTemplates.onCreated('blogList', function () {
      var self = this;
        self.serverBlogCount = new ReactiveVar(false);
        this.autorun(function () {
        Meteor.call('mdBlogCount', function (err, serverBlogCount) {
          self.serverBlogCount.set(serverBlogCount);
        });
      });
    });

    ReactiveTemplates.helpers('blogList', {
      content: function () {
        return marked(this.summary);
      },
      blogControlTemplate: function () {
        return ReactiveTemplates.get('blogControls');
      }
    });

    ReactiveTemplates.events('blogList', {
      'click #mdblog-new': _new
    });

    function _new () {
      if (!Meteor.user()) {
         this.render('not-found');
        return;
      }
```

**Comment by nicolaslopezj** [comment]
All events and handlers are not working or just some of them?

**Comment by thetechnaddict** [comment]
~~It falls over on the first - It seems as though the js file is blank - in other words that the handlers and events are not being assigned to the new template.~~

I really don't know what is happening and need to understand more in order to work out the question.

And I should possibly sleep.

Thanks for your help

**Comment by thetechnaddict** [comment]
tap:i18n is part of the problem - it needs to be set at the project level as well as in the package.

**Comment by thetechnaddict** [comment]
the other problem is

Calls to 
    isInRole('mdblog-author')
when the user with the md_author role is logged in 
give rise to
    Exception from Tracker recompute function:
    Error: No such function: _
         at Blaze.View.lookup (lookup.js:125)
        at Spacebars.call (spacebars-runtime.js:130)
        at Spacebars.mustacheImpl (spacebars-runtime.js:67)
        at Object.Spacebars.mustache (spacebars-runtime.js:71)
        at null._render (template.reclaim_blog_templates.js?    df6a0ef210bf6e29d39193175f84242ec7a48253:21)
        at doRender (view.js:337)
        at view.js:191
        at Function.Template._withTemplateInstanceFunc (template.js:437)
        at view.js:190
        at Object.Blaze._withCurrentView (view.js:523)

**Comment by thetechnaddict** [comment]
```
 {{> Template.dynamic template=blogControlTemplate}}
```

Works within the package template but not in the app template. blogControlTemplate is a function that returns ReactiveTemplates.get('blogControls') - also worked when the code was in the app rather than in a local package.

I think the calls to the UI helpers that grab the classes from the setting.json also do not work in the app 
(which may be the issue with all the i18n code, since that depends on the locale stored in the same settings file.

**Comment by thetechnaddict** [comment]
It seems sorted - I think what did it was back to the first thing you said to me...

```
api.imply([
    'nicolaslopezj:reactive-templates'
     'ogourment:settings'
]);
```

I say think because I am sure I did that hours ago but to no effect - I must have triggered a refresh somehow this time.

**Comment by thetechnaddict** [comment]
So... the solution seems to have been to enable tap:i18n at the project level - which at the minimal was to add the packages (I may experiment with implying them from the package.js) then create a file called project-tap.i18n containing the very minimum, being:

```
{
"helper_name": "_"
}
```

So nothing really to do with ReactiveTemplates AFAIK.

Incidentally I have found this package to be elegantly simple to understand and use, thank you.
