### ISSUE TITLE
Improvement: Pass onRendered and onCreated functions to overriding templates

### ISSUE THREAD

**Issue by sean-stanley** [nicolaslopezj/reactive-templates#4]
It would be nice to also be able to pass onRendered and onCreated functions of the default template to the new function called with:

`ReactiveTemplates.set('template', 'mycustomtemplate')

Maybe a third options parameter could control whether these extras are inherited?

**Comment by nicolaslopezj** [comment]
They are passed, but they must be created with reactive templates api.

If they are not created via reactive templates api it means that it intended to work only with the template, not the ones replacing that one.

**Comment by sean-stanley** [comment]
Oh okay, so when I am overriding admin templates in your OrionJS CMS, I've had to re-initialise materialize js in an onRendered callback to get the materialize css elements working again.

```
  $('#sidenav-overlay').click()
  $('.button-collapse').sideNav()
  $('.dropdown-button').dropdown
    constrain_width: false
```

Is this an issue with OrionJS that I should open? Should this code be being inherited by my custom template rather than re-written?

**Comment by nicolaslopezj** [comment]
That the way it should be. The initializers are there for that specific template, not any layout, thats why its not passed. If you don't use sideNav or dropdown that initializers should be there.
